# Generated by Django 4.1 on 2022-09-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyWatchList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("release_date", models.DateField()),
                ("watched", models.BooleanField(default=False)),
                ("review", models.TextField()),
            ],
        ),
    ]
